/// Demostração de erro por path não encontrado
GET http://localhost:8080/

###
/// Aqui você consferir os blogs registrados
GET http://localhost:8080/posts

###
/// Aqui você pode enviar seu blog
POST http://localhost:8080/posts
Content-type: application/json

{
     "titulo": "Uma nova ",
     "texto": " A era digital veio para cosdfsnquistar o mundo atravéz da tecnologia..."
 
}
###
/// Aqui você pode editar o conteudo do seu blog
PUT http://localhost:8080/posts?id=1
Content-type: application/json

{
    "titulo": "Uma nova era Digital ",
    "texto": " A era digital veio para conquistar o mundo atravéz da tecnologia..."
}

###
/// Aqui você pode deletar algum blog do seu servidor
DELETE  http://localhost:8080/posts?id=12

